# Generated by Django 4.1.5 on 2023-04-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
