# Generated by Django 4.1.5 on 2023-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_transactions_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
